import { useEffect, useMemo, useState } from 'react';
import { initialResume } from './data.js';
import { Builder } from './components/Builder.jsx';
import { Preview } from './components/Preview.jsx';
import { Assistant } from './components/Assistant.jsx';
import { Auth } from './components/Auth.jsx';
import { Dashboard } from './components/Dashboard.jsx';
import { api } from './api.js';
const STORE = 'resumecraft-v1';
const demo = { ...initialResume, personal: { ...initialResume.personal, name: 'Ilhum', title: 'Computer Science Student', email: 'ilhum@email.com', location: 'Dhaka, Bangladesh' }, summary: 'Computer Science student with hands-on experience building thoughtful web applications and conducting data-driven research.', skills: ['JavaScript', 'React', 'Python', 'Research'], education: [{ id: 'd', school: 'University of Dhaka', degree: 'BSc', field: 'Computer Science', start: '2022-01', end: '2026-01' }], projects: [{ id: 'p', name: 'Campus Connect', tech: 'React · Node.js', description: 'Built a student collaboration platform with a focused, accessible interface.' }] };
export default function App() {
  const [screen, setScreen] = useState('home'); const [user, setUser] = useState(null); const [resumeId, setResumeId] = useState(null); const [mobile, setMobile] = useState('form');
  const [resume, setResume] = useState(() => { try { return { ...initialResume, ...JSON.parse(localStorage.getItem(STORE)) }; } catch { return initialResume; } }); const [saved, setSaved] = useState('Saved locally');
  useEffect(() => { setSaved('Saving…'); const timer = setTimeout(() => { localStorage.setItem(STORE, JSON.stringify(resume)); setSaved('Saved locally'); }, 500); return () => clearTimeout(timer); }, [resume]);
  const completion = useMemo(() => Math.round([resume.personal.name, resume.personal.email, resume.summary, resume.skills.length, resume.education.length, resume.projects.length].filter(Boolean).length / 6 * 100), [resume]);
  function exportPdf() {
    const preview = document.querySelector('.preview-pane .paper');
    if (!preview) return;
    const popup = window.open('', '_blank', 'width=900,height=900');
    if (!popup) { window.print(); return; }
    popup.opener = null;
    const styles = Array.from(document.querySelectorAll('style,link[rel="stylesheet"]')).map(node => node.outerHTML).join('');
    popup.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${resume.personal.name || 'Resume'} – ResumeCraft</title>${styles}<style>@page{size:A4;margin:0}html,body{margin:0!important;padding:0!important;background:#fff!important}.paper{width:210mm!important;max-width:none!important;min-height:297mm!important;margin:0!important;box-shadow:none!important;padding:14mm!important}.paper section{break-inside:avoid}</style></head><body>${preview.outerHTML}<script>window.onload=()=>setTimeout(()=>window.print(),250);window.onafterprint=()=>window.close();<\/script></body></html>`);
    popup.document.close();
  }
  async function saveAccountResume() { if (!user) return setScreen('login'); setSaved('Saving to account…'); try { if (resumeId) await api(`/api/resumes/${resumeId}`, { method: 'PUT', body: JSON.stringify({ title: resume.title, data: resume }) }); else { const result = await api('/api/resumes', { method: 'POST', body: JSON.stringify({ title: resume.title, data: resume }) }); setResumeId(result.data.id); } setSaved('Saved to account'); } catch (e) { setSaved(e.message); } }
  async function openSaved(id) { try { const item = await api(`/api/resumes/${id}`); setResume({ ...initialResume, ...item.data.data }); setResumeId(id); setScreen('builder'); } catch { setScreen('dashboard'); } }
  if (screen === 'login' || screen === 'register') return <Auth mode={screen} onSuccess={account => { setUser(account); setScreen('dashboard'); }} onBack={target => setScreen(target || 'home')}/>;
  if (screen === 'dashboard') return <><header className="topbar"><button className="brand link" onClick={() => setScreen('home')}>✦ ResumeCraft <span>AI</span></button></header><Dashboard user={user} onNew={() => { setResume(initialResume); setResumeId(null); setScreen('builder'); }} onEdit={openSaved} onLogout={async () => { await api('/api/auth/logout', { method: 'POST' }); setUser(null); setScreen('home'); }}/></>;
  if (screen === 'home') return <><header className="topbar"><a className="brand" href="#top">✦ ResumeCraft <span>AI</span></a><nav><a href="#features">Features</a><button className="link" onClick={() => setScreen('login')}>Log in</button><button className="primary small" onClick={() => setScreen('register')}>Create account</button></nav></header><main id="top"><section className="hero"><div><p className="eyebrow">YOUR CAREER, CLEARLY PRESENTED</p><h1>Build a professional resume with <i>AI</i>.</h1><p className="lede">A calm, guided workspace for students and early-career professionals. Turn your real experiences into a resume you are proud to send.</p><div className="hero-actions"><button className="primary" onClick={() => setScreen('builder')}>Create my resume <span>→</span></button><a href="#how">See how it works</a></div><p className="trust">No account required · Your draft stays in your browser</p></div><div className="hero-paper"><Preview resume={demo}/></div></section><section className="features" id="features"><p className="eyebrow">DESIGNED FOR YOUR FIRST GREAT IMPRESSION</p><h2>Everything you need. Nothing to overwhelm you.</h2><div className="feature-grid"><article><b>01</b><h3>Guided from the start</h3><p>Clear prompts and useful examples make every field easier to complete.</p></article><article><b>02</b><h3>Thoughtful AI help</h3><p>Get stronger wording and practical questions—without made-up achievements.</p></article><article><b>03</b><h3>Ready to send</h3><p>See your resume update live and export a clean, selectable-text PDF.</p></article></div></section><section className="how" id="how"><p className="eyebrow">SIMPLE BY DESIGN</p><h2>From blank page to polished resume in three steps.</h2><ol><li><span>1</span> Share your background</li><li><span>2</span> Refine it with AI</li><li><span>3</span> Download with confidence</li></ol></section></main><footer>© 2026 ResumeCraft AI · Built to help you tell your real story.</footer></>;
  return <div className="app"><header className="topbar"><button className="brand link" onClick={() => setScreen(user ? 'dashboard' : 'home')}>✦ ResumeCraft <span>AI</span></button><div className="status"><span className="dot"/> {saved}</div><div><button className="save-account" onClick={saveAccountResume}>{user ? 'Save to account' : 'Log in to save'}</button> <button className="download" onClick={exportPdf}>Download PDF</button></div></header><div className="builder-top"><div><input className="title-input" aria-label="Resume title" value={resume.title} onChange={e => setResume(r => ({ ...r, title: e.target.value }))}/><p>Target role <input value={resume.targetRole} onChange={e => setResume(r => ({ ...r, targetRole: e.target.value }))} placeholder="e.g. Frontend developer"/></p></div><div className="progress"><span>{completion}% complete</span><div><i style={{ width: `${completion}%` }}/></div></div><div className="controls"><label>Template<select value={resume.template} onChange={e => setResume(r => ({ ...r, template: e.target.value }))}><option value="modern">Modern</option><option value="minimal">Minimal</option><option value="academic">Academic</option></select></label><label>Accent<input type="color" value={resume.accent} onChange={e => setResume(r => ({ ...r, accent: e.target.value }))}/></label></div></div><div className="mobile-tabs"><button className={mobile === 'form' ? 'active' : ''} onClick={() => setMobile('form')}>Form</button><button className={mobile === 'ai' ? 'active' : ''} onClick={() => setMobile('ai')}>AI assistant</button><button className={mobile === 'preview' ? 'active' : ''} onClick={() => setMobile('preview')}>Preview</button></div><div className="workspace"><div className={`form-pane ${mobile !== 'form' ? 'mobile-hidden' : ''}`}><Builder resume={resume} setResume={setResume}/></div><div className={`preview-pane ${mobile !== 'preview' ? 'mobile-hidden' : ''}`}><Preview resume={resume}/></div><div className={`ai-pane ${mobile !== 'ai' ? 'mobile-hidden' : ''}`}><Assistant resume={resume} onSummary={summary => setResume(r => ({ ...r, summary }))}/></div></div></div>;
}
