import { db } from './database.js';
import { requireUser } from './auth.js';
export function resumeRoutes(app) {
  app.get('/api/resumes', requireUser, async (req, res, next) => { try { const query = await db(); const rows = await query`SELECT id, title, updated_at FROM resumes WHERE user_id=${req.userId} ORDER BY updated_at DESC`; res.json({ success: true, data: rows }); } catch (error) { next(error); } });
  app.post('/api/resumes', requireUser, async (req, res, next) => { try { const { title, data } = req.body || {}; if (!title || !data || typeof data !== 'object') return res.status(400).json({ success: false, message: 'A title and resume data are required.' }); const query = await db(); const rows = await query`INSERT INTO resumes (user_id, title, data) VALUES (${req.userId}, ${title.slice(0, 120)}, ${JSON.stringify(data)}::jsonb) RETURNING id`; res.status(201).json({ success: true, data: rows[0] }); } catch (error) { next(error); } });
  app.get('/api/resumes/:id', requireUser, async (req, res, next) => { try { const query = await db(); const rows = await query`SELECT id, title, data, updated_at FROM resumes WHERE id=${req.params.id} AND user_id=${req.userId}`; if (!rows[0]) return res.status(404).json({ success: false, message: 'Resume not found.' }); res.json({ success: true, data: rows[0] }); } catch (error) { next(error); } });
  app.put('/api/resumes/:id', requireUser, async (req, res, next) => { try { const { title, data } = req.body || {}; const query = await db(); const rows = await query`UPDATE resumes SET title=${title?.slice(0, 120) || 'Untitled resume'}, data=${JSON.stringify(data || {})}::jsonb, updated_at=NOW() WHERE id=${req.params.id} AND user_id=${req.userId} RETURNING id`; if (!rows[0]) return res.status(404).json({ success: false, message: 'Resume not found.' }); res.json({ success: true }); } catch (error) { next(error); } });
  app.delete('/api/resumes/:id', requireUser, async (req, res, next) => { try { const query = await db(); const rows = await query`DELETE FROM resumes WHERE id=${req.params.id} AND user_id=${req.userId} RETURNING id`; if (!rows[0]) return res.status(404).json({ success: false, message: 'Resume not found.' }); res.status(204).end(); } catch (error) { next(error); } });
}
