import { useState } from 'react';
import { aiRequest } from '../api.js';
export function Assistant({ resume, onSummary }) {
  const [messages, setMessages] = useState([{ role: 'ai', text: 'Hi! What role, internship, or opportunity are you targeting? I’ll help you make each section clear and accurate.' }]);
  const [input, setInput] = useState(''); const [busy, setBusy] = useState(false);
  async function send(text = input) { if (!text.trim() || busy) return; setMessages(m => [...m, { role: 'user', text }]); setInput(''); setBusy(true); try { const data = await aiRequest('chat', { message: text, resume }); setMessages(m => [...m, { role: 'ai', text: data.assistantMessage, question: data.followUpQuestion }]); } catch (e) { setMessages(m => [...m, { role: 'ai error', text: e.message }]); } finally { setBusy(false); } }
  async function summary() { setBusy(true); try { const data = await aiRequest('generate-summary', { resume, tone: 'professional' }); onSummary(data.summary); setMessages(m => [...m, { role: 'ai', text: 'I generated a draft summary. Please review it and keep only what is accurate.' }]); } catch (e) { setMessages(m => [...m, { role: 'ai error', text: e.message }]); } finally { setBusy(false); } }
  return <aside className="assistant"><div className="assistant-title"><span>✦</span><div><strong>ResumeCraft AI</strong><small>Suggestions need your approval</small></div></div><div className="messages">{messages.map((m, i) => <div key={i} className={`message ${m.role}`}><p>{m.text}</p>{m.question && <p className="question">{m.question}</p>}</div>)}{busy && <div className="message ai"><p>Thinking…</p></div>}</div><div className="quick"><button onClick={summary} disabled={busy}>Generate summary</button><button onClick={() => send('Review my resume and tell me the highest-priority missing information.')} disabled={busy}>Review my resume</button></div><form onSubmit={e => { e.preventDefault(); send(); }}><label className="sr-only" htmlFor="chat">Message the assistant</label><div className="chat-input"><input id="chat" value={input} onChange={e => setInput(e.target.value)} placeholder="Ask for help…"/><button aria-label="Send message" disabled={busy}>↑</button></div></form></aside>;
}
