import { useState } from 'react';
import { emptyItem, sectionLabels } from '../data.js';
const fields = { personal: [['name', 'Full name', 'Ilhum ul hoque'], ['title', 'Professional title', 'Computer Science student'], ['email', 'Email', 'ilhum@email.com'], ['phone', 'Phone', '+880…'], ['location', 'Location', 'Dhaka, Bangladesh'], ['linkedin', 'LinkedIn URL', 'linkedin.com/in/…'], ['github', 'GitHub URL', 'github.com/…'], ['portfolio', 'Portfolio URL', 'ilhumulhoque.dev']] };
function Input({ label, value, onChange, placeholder, type = 'text' }) { return <label>{label}<input type={type} value={value || ''} placeholder={placeholder} onChange={e => onChange(e.target.value)} /></label>; }
function Repeater({ items, onChange, fields, addLabel }) { const update = (id, field, value) => onChange(items.map(x => x.id === id ? { ...x, [field]: value } : x)); return <>{items.map((item, index) => <fieldset className="record" key={item.id}><legend>{addLabel} {index + 1}</legend><button className="remove" onClick={() => onChange(items.filter(x => x.id !== item.id))} type="button" aria-label={`Remove ${addLabel}`}>×</button><div className="field-grid">{fields.map(([key, label, type]) => type === 'textarea' ? <label key={key} className="full">{label}<textarea value={item[key] || ''} onChange={e => update(item.id, key, e.target.value)} /></label> : <Input key={key} label={label} type={type || 'text'} value={item[key]} onChange={value => update(item.id, key, value)} />)}</div></fieldset>)}<button className="add" type="button" onClick={() => onChange([...items, emptyItem()])}>+ Add {addLabel.toLowerCase()}</button></>; }
export function Builder({ resume, setResume }) {
  const [active, setActive] = useState('personal');
  const set = (path, value) => setResume(r => ({ ...r, [path]: value }));
  const updatePersonal = (key, value) => setResume(r => ({ ...r, personal: { ...r.personal, [key]: value } }));
  let content;
  if (active === 'personal') content = <div className="field-grid">{fields.personal.map(([key, label, placeholder]) => <Input key={key} label={label} placeholder={placeholder} value={resume.personal[key]} onChange={value => updatePersonal(key, value)} />)}</div>;
  if (active === 'summary') content = <><label>Summary<textarea rows="7" value={resume.summary} onChange={e => set('summary', e.target.value)} placeholder="Briefly describe your relevant strengths, education, and goals. You can ask AI to draft it." /></label><p className="hint">Keep it to 2–4 sentences. Avoid generic claims that you cannot support.</p></>;
  if (active === 'skills') content = <><label>Skills (separate with commas)<textarea rows="6" value={resume.skills.join(', ')} onChange={e => set('skills', e.target.value.split(',').map(x => x.trim()).filter(Boolean))} placeholder="JavaScript, React, Research, Teamwork" /></label><p className="hint">Only include skills you can confidently discuss.</p></>;
  if (active === 'education') content = <Repeater items={resume.education} onChange={v => set('education', v)} addLabel="Education" fields={[["school", "Institution"], ["degree", "Degree"], ["field", "Field of study"], ["start", "Start date", "month"], ["end", "End / expected", "month"], ["gpa", "CGPA / GPA"], ["description", "Coursework or achievement", "textarea"]]} />;
  if (active === 'projects') content = <Repeater items={resume.projects} onChange={v => set('projects', v)} addLabel="Project" fields={[["name", "Project name"], ["url", "Project URL"], ["tech", "Technologies"], ["description", "Contribution, problem, or result", "textarea"]]} />;
  if (active === 'research') content = <Repeater items={resume.research} onChange={v => set('research', v)} addLabel="Research item" fields={[["title", "Research or paper title"], ["venue", "Publication / conference"], ["year", "Year"], ["description", "Contribution or findings", "textarea"]]} />;
  if (active === 'activities') content = <Repeater items={resume.activities} onChange={v => set('activities', v)} addLabel="Activity" fields={[["organization", "Organization or club"], ["role", "Position or role"], ["description", "Responsibilities or achievement", "textarea"]]} />;
  if (active === 'languages') content = <Repeater items={resume.languages} onChange={v => set('languages', v)} addLabel="Language" fields={[["name", "Language"], ["level", "Proficiency (e.g. Fluent)"]]} />;
  return <div className="builder"><nav className="section-nav" aria-label="Resume sections">{Object.entries(sectionLabels).map(([id, label]) => <button key={id} className={id === active ? 'active' : ''} onClick={() => setActive(id)}>{label}</button>)}</nav><main className="form-card"><div className="form-heading"><div><p className="eyebrow">Resume section</p><h2>{sectionLabels[active]}</h2></div><span className="step">{Object.keys(sectionLabels).indexOf(active) + 1} / 8</span></div>{content}</main></div>;
}
